CanvasRenderingContext2D = function CanvasRenderingContext2D(){
    sandbox_vm2.throwError("TypeError", "Illegal constructor") 
}
sandbox_vm2.func_set_native(CanvasRenderingContext2D)
sandbox_vm2.rename(CanvasRenderingContext2D.prototype, "CanvasRenderingContext2D")

// 设置属性参数 function defineProperty(obj, key, value, configurable, enumerable, writable, getter, setter) {...}




sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'canvas', undefined, true, true, undefined, function () {return undefined},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["canvas"].get, "get canvas");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'globalAlpha', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["globalAlpha"].get, "get globalAlpha");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["globalAlpha"].set, "set globalAlpha");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'globalCompositeOperation', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["globalCompositeOperation"].get, "get globalCompositeOperation");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["globalCompositeOperation"].set, "set globalCompositeOperation");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'filter', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["filter"].get, "get filter");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["filter"].set, "set filter");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'imageSmoothingEnabled', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["imageSmoothingEnabled"].get, "get imageSmoothingEnabled");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["imageSmoothingEnabled"].set, "set imageSmoothingEnabled");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'imageSmoothingQuality', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["imageSmoothingQuality"].get, "get imageSmoothingQuality");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["imageSmoothingQuality"].set, "set imageSmoothingQuality");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'strokeStyle', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["strokeStyle"].get, "get strokeStyle");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["strokeStyle"].set, "set strokeStyle");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'fillStyle', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fillStyle"].get, "get fillStyle");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fillStyle"].set, "set fillStyle");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'shadowOffsetX', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowOffsetX"].get, "get shadowOffsetX");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowOffsetX"].set, "set shadowOffsetX");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'shadowOffsetY', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowOffsetY"].get, "get shadowOffsetY");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowOffsetY"].set, "set shadowOffsetY");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'shadowBlur', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowBlur"].get, "get shadowBlur");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowBlur"].set, "set shadowBlur");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'shadowColor', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowColor"].get, "get shadowColor");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowColor"].set, "set shadowColor");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'lineWidth', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineWidth"].get, "get lineWidth");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineWidth"].set, "set lineWidth");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'lineCap', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineCap"].get, "get lineCap");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineCap"].set, "set lineCap");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'lineJoin', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineJoin"].get, "get lineJoin");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineJoin"].set, "set lineJoin");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'miterLimit', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["miterLimit"].get, "get miterLimit");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["miterLimit"].set, "set miterLimit");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'lineDashOffset', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineDashOffset"].get, "get lineDashOffset");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineDashOffset"].set, "set lineDashOffset");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'font', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["font"].get, "get font");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["font"].set, "set font");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'textAlign', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textAlign"].get, "get textAlign");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textAlign"].set, "set textAlign");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'textBaseline', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textBaseline"].get, "get textBaseline");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textBaseline"].set, "set textBaseline");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'direction', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["direction"].get, "get direction");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["direction"].set, "set direction");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'fontKerning', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontKerning"].get, "get fontKerning");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontKerning"].set, "set fontKerning");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'fontStretch', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontStretch"].get, "get fontStretch");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontStretch"].set, "set fontStretch");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'fontVariantCaps', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontVariantCaps"].get, "get fontVariantCaps");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontVariantCaps"].set, "set fontVariantCaps");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'letterSpacing', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["letterSpacing"].get, "get letterSpacing");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["letterSpacing"].set, "set letterSpacing");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'textRendering', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textRendering"].get, "get textRendering");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textRendering"].set, "set textRendering");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'wordSpacing', undefined, true, true, undefined, function () {return undefined},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["wordSpacing"].get, "get wordSpacing");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["wordSpacing"].set, "set wordSpacing");
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'clip', function clip(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.clip)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'createConicGradient', function createConicGradient(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.createConicGradient)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'createImageData', function createImageData(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.createImageData)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'createLinearGradient', function createLinearGradient(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.createLinearGradient)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'createPattern', function createPattern(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.createPattern)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'createRadialGradient', function createRadialGradient(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.createRadialGradient)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'drawFocusIfNeeded', function drawFocusIfNeeded(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.drawFocusIfNeeded)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'drawImage', function drawImage(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.drawImage)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'fill', function fill(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.fill)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'fillText', function fillText(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.fillText)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'getContextAttributes', function getContextAttributes(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.getContextAttributes)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'getImageData', function getImageData(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.getImageData)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'getLineDash', function getLineDash(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.getLineDash)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'getTransform', function getTransform(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.getTransform)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'isContextLost', function isContextLost(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.isContextLost)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'isPointInPath', function isPointInPath(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.isPointInPath)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'isPointInStroke', function isPointInStroke(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.isPointInStroke)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'measureText', function measureText(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.measureText)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'putImageData', function putImageData(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.putImageData)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'reset', function reset(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.reset)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'roundRect', function roundRect(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.roundRect)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'save', function save(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.save)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'scale', function scale(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.scale)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'setLineDash', function setLineDash(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.setLineDash)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'setTransform', function setTransform(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.setTransform)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'stroke', function stroke(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.stroke)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'strokeText', function strokeText(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.strokeText)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'transform', function transform(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.transform)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'translate', function translate(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.translate)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'arc', function arc(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.arc)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'arcTo', function arcTo(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.arcTo)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'beginPath', function beginPath(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.beginPath)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'bezierCurveTo', function bezierCurveTo(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.bezierCurveTo)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'clearRect', function clearRect(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.clearRect)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'closePath', function closePath(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.closePath)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'ellipse', function ellipse(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.ellipse)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'fillRect', function fillRect(x,y,w,h){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.fillRect)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'lineTo', function lineTo(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.lineTo)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'moveTo', function moveTo(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.moveTo)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'quadraticCurveTo', function quadraticCurveTo(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.quadraticCurveTo)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'rect', function rect(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.rect)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'resetTransform', function resetTransform(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.resetTransform)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'restore', function restore(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.restore)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'rotate', function rotate(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.rotate)
sandbox_vm2.defineProperty(CanvasRenderingContext2D.prototype, 'strokeRect', function strokeRect(){debugger;}, true, true, true); sandbox_vm2.func_set_native(CanvasRenderingContext2D.prototype.strokeRect)

