Document = function Document(){debugger;
}
sandbox_vm2.func_set_native(Document)
sandbox_vm2.rename(Document.prototype, "Document")
 
Object.setPrototypeOf(Document.prototype,Node.prototype)
sandbox_vm2.defineProperty(Document.prototype, 'implementation', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["implementation"].get, "get implementation");
sandbox_vm2.defineProperty(Document.prototype, 'URL', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["URL"].get, "get URL");
sandbox_vm2.defineProperty(Document.prototype, 'documentURI', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["documentURI"].get, "get documentURI");
sandbox_vm2.defineProperty(Document.prototype, 'compatMode', undefined, true, true, undefined, function () {
    return "CSS1Compat";
},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["compatMode"].get, "get compatMode");
sandbox_vm2.defineProperty(Document.prototype, 'characterSet', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["characterSet"].get, "get characterSet");
sandbox_vm2.defineProperty(Document.prototype, 'charset', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["charset"].get, "get charset");
sandbox_vm2.defineProperty(Document.prototype, 'inputEncoding', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["inputEncoding"].get, "get inputEncoding");
sandbox_vm2.defineProperty(Document.prototype, 'contentType', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["contentType"].get, "get contentType");
sandbox_vm2.defineProperty(Document.prototype, 'doctype', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["doctype"].get, "get doctype");
sandbox_vm2.defineProperty(Document.prototype, 'documentElement', undefined, true, true, undefined, function () {
    let h = "<html><head><title></title></head> <body></body></html>";
    Object.setPrototypeOf(h, HTMLHtmlElement.prototype);
    return h

},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["documentElement"].get, "get documentElement");
sandbox_vm2.defineProperty(Document.prototype, 'xmlEncoding', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["xmlEncoding"].get, "get xmlEncoding");
sandbox_vm2.defineProperty(Document.prototype, 'xmlVersion', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["xmlVersion"].get, "get xmlVersion");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["xmlVersion"].set, "set xmlVersion");
sandbox_vm2.defineProperty(Document.prototype, 'xmlStandalone', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["xmlStandalone"].get, "get xmlStandalone");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["xmlStandalone"].set, "set xmlStandalone");
sandbox_vm2.defineProperty(Document.prototype, 'domain', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["domain"].get, "get domain");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["domain"].set, "set domain");
sandbox_vm2.defineProperty(Document.prototype, 'referrer', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["referrer"].get, "get referrer");
sandbox_vm2.defineProperty(Document.prototype, 'cookie', undefined, true, true, undefined, function () {debugger;},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["cookie"].get, "get cookie");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["cookie"].set, "set cookie");
sandbox_vm2.defineProperty(Document.prototype, 'lastModified', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["lastModified"].get, "get lastModified");
sandbox_vm2.defineProperty(Document.prototype, 'readyState', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["readyState"].get, "get readyState");
sandbox_vm2.defineProperty(Document.prototype, 'title', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["title"].get, "get title");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["title"].set, "set title");
sandbox_vm2.defineProperty(Document.prototype, 'dir', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["dir"].get, "get dir");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["dir"].set, "set dir");
sandbox_vm2.defineProperty(Document.prototype, 'body', undefined, true, true, undefined, function () {

    let body = "<body></body>";
    Object.setPrototypeOf(body, HTMLBodyElement.prototype);

    return body;

},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["body"].get, "get body");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["body"].set, "set body");
sandbox_vm2.defineProperty(Document.prototype, 'head', undefined, true, true, undefined, function () {
    let head = "<head></head>";
    Object.setPrototypeOf(head, HTMLHeadElement.prototype);

    return head;
},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["head"].get, "get head");
sandbox_vm2.defineProperty(Document.prototype, 'images', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["images"].get, "get images");
sandbox_vm2.defineProperty(Document.prototype, 'embeds', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["embeds"].get, "get embeds");
sandbox_vm2.defineProperty(Document.prototype, 'plugins', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["plugins"].get, "get plugins");
sandbox_vm2.defineProperty(Document.prototype, 'links', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["links"].get, "get links");
sandbox_vm2.defineProperty(Document.prototype, 'forms', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["forms"].get, "get forms");
sandbox_vm2.defineProperty(Document.prototype, 'scripts', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["scripts"].get, "get scripts");
sandbox_vm2.defineProperty(Document.prototype, 'currentScript', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["currentScript"].get, "get currentScript");
sandbox_vm2.defineProperty(Document.prototype, 'defaultView', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["defaultView"].get, "get defaultView");
sandbox_vm2.defineProperty(Document.prototype, 'designMode', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["designMode"].get, "get designMode");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["designMode"].set, "set designMode");
sandbox_vm2.defineProperty(Document.prototype, 'onreadystatechange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onreadystatechange"].get, "get onreadystatechange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onreadystatechange"].set, "set onreadystatechange");
sandbox_vm2.defineProperty(Document.prototype, 'anchors', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["anchors"].get, "get anchors");
sandbox_vm2.defineProperty(Document.prototype, 'applets', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["applets"].get, "get applets");
sandbox_vm2.defineProperty(Document.prototype, 'fgColor', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["fgColor"].get, "get fgColor");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["fgColor"].set, "set fgColor");
sandbox_vm2.defineProperty(Document.prototype, 'linkColor', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["linkColor"].get, "get linkColor");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["linkColor"].set, "set linkColor");
sandbox_vm2.defineProperty(Document.prototype, 'vlinkColor', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["vlinkColor"].get, "get vlinkColor");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["vlinkColor"].set, "set vlinkColor");
sandbox_vm2.defineProperty(Document.prototype, 'alinkColor', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["alinkColor"].get, "get alinkColor");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["alinkColor"].set, "set alinkColor");
sandbox_vm2.defineProperty(Document.prototype, 'bgColor', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["bgColor"].get, "get bgColor");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["bgColor"].set, "set bgColor");
sandbox_vm2.defineProperty(Document.prototype, 'all', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["all"].get, "get all");
sandbox_vm2.defineProperty(Document.prototype, 'scrollingElement', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["scrollingElement"].get, "get scrollingElement");
sandbox_vm2.defineProperty(Document.prototype, 'onpointerlockchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerlockchange"].get, "get onpointerlockchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerlockchange"].set, "set onpointerlockchange");
sandbox_vm2.defineProperty(Document.prototype, 'onpointerlockerror', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerlockerror"].get, "get onpointerlockerror");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerlockerror"].set, "set onpointerlockerror");
sandbox_vm2.defineProperty(Document.prototype, 'hidden', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["hidden"].get, "get hidden");
sandbox_vm2.defineProperty(Document.prototype, 'visibilityState', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["visibilityState"].get, "get visibilityState");
sandbox_vm2.defineProperty(Document.prototype, 'wasDiscarded', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["wasDiscarded"].get, "get wasDiscarded");
sandbox_vm2.defineProperty(Document.prototype, 'featurePolicy', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["featurePolicy"].get, "get featurePolicy");
sandbox_vm2.defineProperty(Document.prototype, 'webkitVisibilityState', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["webkitVisibilityState"].get, "get webkitVisibilityState");
sandbox_vm2.defineProperty(Document.prototype, 'webkitHidden', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["webkitHidden"].get, "get webkitHidden");
sandbox_vm2.defineProperty(Document.prototype, 'onbeforecopy', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforecopy"].get, "get onbeforecopy");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforecopy"].set, "set onbeforecopy");
sandbox_vm2.defineProperty(Document.prototype, 'onbeforecut', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforecut"].get, "get onbeforecut");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforecut"].set, "set onbeforecut");
sandbox_vm2.defineProperty(Document.prototype, 'onbeforepaste', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforepaste"].get, "get onbeforepaste");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforepaste"].set, "set onbeforepaste");
sandbox_vm2.defineProperty(Document.prototype, 'onfreeze', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onfreeze"].get, "get onfreeze");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onfreeze"].set, "set onfreeze");
sandbox_vm2.defineProperty(Document.prototype, 'onresume', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onresume"].get, "get onresume");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onresume"].set, "set onresume");
sandbox_vm2.defineProperty(Document.prototype, 'onsearch', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onsearch"].get, "get onsearch");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onsearch"].set, "set onsearch");
sandbox_vm2.defineProperty(Document.prototype, 'onvisibilitychange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onvisibilitychange"].get, "get onvisibilitychange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onvisibilitychange"].set, "set onvisibilitychange");
sandbox_vm2.defineProperty(Document.prototype, 'fullscreenEnabled', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreenEnabled"].get, "get fullscreenEnabled");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreenEnabled"].set, "set fullscreenEnabled");
sandbox_vm2.defineProperty(Document.prototype, 'fullscreen', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreen"].get, "get fullscreen");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreen"].set, "set fullscreen");
sandbox_vm2.defineProperty(Document.prototype, 'onfullscreenchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onfullscreenchange"].get, "get onfullscreenchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onfullscreenchange"].set, "set onfullscreenchange");
sandbox_vm2.defineProperty(Document.prototype, 'onfullscreenerror', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onfullscreenerror"].get, "get onfullscreenerror");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onfullscreenerror"].set, "set onfullscreenerror");
sandbox_vm2.defineProperty(Document.prototype, 'webkitIsFullScreen', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["webkitIsFullScreen"].get, "get webkitIsFullScreen");
sandbox_vm2.defineProperty(Document.prototype, 'webkitCurrentFullScreenElement', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["webkitCurrentFullScreenElement"].get, "get webkitCurrentFullScreenElement");
sandbox_vm2.defineProperty(Document.prototype, 'webkitFullscreenEnabled', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["webkitFullscreenEnabled"].get, "get webkitFullscreenEnabled");
sandbox_vm2.defineProperty(Document.prototype, 'webkitFullscreenElement', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["webkitFullscreenElement"].get, "get webkitFullscreenElement");
sandbox_vm2.defineProperty(Document.prototype, 'onwebkitfullscreenchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitfullscreenchange"].get, "get onwebkitfullscreenchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitfullscreenchange"].set, "set onwebkitfullscreenchange");
sandbox_vm2.defineProperty(Document.prototype, 'onwebkitfullscreenerror', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitfullscreenerror"].get, "get onwebkitfullscreenerror");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitfullscreenerror"].set, "set onwebkitfullscreenerror");
sandbox_vm2.defineProperty(Document.prototype, 'rootElement', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["rootElement"].get, "get rootElement");
sandbox_vm2.defineProperty(Document.prototype, 'pictureInPictureEnabled', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["pictureInPictureEnabled"].get, "get pictureInPictureEnabled");
sandbox_vm2.defineProperty(Document.prototype, 'pictureInPictureElement', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["pictureInPictureElement"].get, "get pictureInPictureElement");
sandbox_vm2.defineProperty(Document.prototype, 'onbeforexrselect', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforexrselect"].get, "get onbeforexrselect");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforexrselect"].set, "set onbeforexrselect");
sandbox_vm2.defineProperty(Document.prototype, 'onabort', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onabort"].get, "get onabort");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onabort"].set, "set onabort");
sandbox_vm2.defineProperty(Document.prototype, 'onbeforeinput', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforeinput"].get, "get onbeforeinput");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforeinput"].set, "set onbeforeinput");
sandbox_vm2.defineProperty(Document.prototype, 'onblur', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onblur"].get, "get onblur");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onblur"].set, "set onblur");
sandbox_vm2.defineProperty(Document.prototype, 'oncancel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncancel"].get, "get oncancel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncancel"].set, "set oncancel");
sandbox_vm2.defineProperty(Document.prototype, 'oncanplay', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncanplay"].get, "get oncanplay");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncanplay"].set, "set oncanplay");
sandbox_vm2.defineProperty(Document.prototype, 'oncanplaythrough', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncanplaythrough"].get, "get oncanplaythrough");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncanplaythrough"].set, "set oncanplaythrough");
sandbox_vm2.defineProperty(Document.prototype, 'onchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onchange"].get, "get onchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onchange"].set, "set onchange");
sandbox_vm2.defineProperty(Document.prototype, 'onclick', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onclick"].get, "get onclick");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onclick"].set, "set onclick");
sandbox_vm2.defineProperty(Document.prototype, 'onclose', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onclose"].get, "get onclose");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onclose"].set, "set onclose");
sandbox_vm2.defineProperty(Document.prototype, 'oncontextlost', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextlost"].get, "get oncontextlost");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextlost"].set, "set oncontextlost");
sandbox_vm2.defineProperty(Document.prototype, 'oncontextmenu', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextmenu"].get, "get oncontextmenu");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextmenu"].set, "set oncontextmenu");
sandbox_vm2.defineProperty(Document.prototype, 'oncontextrestored', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextrestored"].get, "get oncontextrestored");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextrestored"].set, "set oncontextrestored");
sandbox_vm2.defineProperty(Document.prototype, 'oncuechange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncuechange"].get, "get oncuechange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncuechange"].set, "set oncuechange");
sandbox_vm2.defineProperty(Document.prototype, 'ondblclick', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondblclick"].get, "get ondblclick");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondblclick"].set, "set ondblclick");
sandbox_vm2.defineProperty(Document.prototype, 'ondrag', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondrag"].get, "get ondrag");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondrag"].set, "set ondrag");
sandbox_vm2.defineProperty(Document.prototype, 'ondragend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondragend"].get, "get ondragend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondragend"].set, "set ondragend");
sandbox_vm2.defineProperty(Document.prototype, 'ondragenter', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondragenter"].get, "get ondragenter");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondragenter"].set, "set ondragenter");
sandbox_vm2.defineProperty(Document.prototype, 'ondragleave', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondragleave"].get, "get ondragleave");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondragleave"].set, "set ondragleave");
sandbox_vm2.defineProperty(Document.prototype, 'ondragover', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondragover"].get, "get ondragover");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondragover"].set, "set ondragover");
sandbox_vm2.defineProperty(Document.prototype, 'ondragstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondragstart"].get, "get ondragstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondragstart"].set, "set ondragstart");
sandbox_vm2.defineProperty(Document.prototype, 'ondrop', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondrop"].get, "get ondrop");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondrop"].set, "set ondrop");
sandbox_vm2.defineProperty(Document.prototype, 'ondurationchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondurationchange"].get, "get ondurationchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ondurationchange"].set, "set ondurationchange");
sandbox_vm2.defineProperty(Document.prototype, 'onemptied', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onemptied"].get, "get onemptied");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onemptied"].set, "set onemptied");
sandbox_vm2.defineProperty(Document.prototype, 'onended', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onended"].get, "get onended");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onended"].set, "set onended");
sandbox_vm2.defineProperty(Document.prototype, 'onerror', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onerror"].get, "get onerror");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onerror"].set, "set onerror");
sandbox_vm2.defineProperty(Document.prototype, 'onfocus', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onfocus"].get, "get onfocus");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onfocus"].set, "set onfocus");
sandbox_vm2.defineProperty(Document.prototype, 'onformdata', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onformdata"].get, "get onformdata");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onformdata"].set, "set onformdata");
sandbox_vm2.defineProperty(Document.prototype, 'oninput', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oninput"].get, "get oninput");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oninput"].set, "set oninput");
sandbox_vm2.defineProperty(Document.prototype, 'oninvalid', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oninvalid"].get, "get oninvalid");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oninvalid"].set, "set oninvalid");
sandbox_vm2.defineProperty(Document.prototype, 'onkeydown', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onkeydown"].get, "get onkeydown");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onkeydown"].set, "set onkeydown");
sandbox_vm2.defineProperty(Document.prototype, 'onkeypress', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onkeypress"].get, "get onkeypress");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onkeypress"].set, "set onkeypress");
sandbox_vm2.defineProperty(Document.prototype, 'onkeyup', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onkeyup"].get, "get onkeyup");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onkeyup"].set, "set onkeyup");
sandbox_vm2.defineProperty(Document.prototype, 'onload', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onload"].get, "get onload");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onload"].set, "set onload");
sandbox_vm2.defineProperty(Document.prototype, 'onloadeddata', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onloadeddata"].get, "get onloadeddata");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onloadeddata"].set, "set onloadeddata");
sandbox_vm2.defineProperty(Document.prototype, 'onloadedmetadata', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onloadedmetadata"].get, "get onloadedmetadata");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onloadedmetadata"].set, "set onloadedmetadata");
sandbox_vm2.defineProperty(Document.prototype, 'onloadstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onloadstart"].get, "get onloadstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onloadstart"].set, "set onloadstart");
sandbox_vm2.defineProperty(Document.prototype, 'onmousedown', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmousedown"].get, "get onmousedown");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmousedown"].set, "set onmousedown");
sandbox_vm2.defineProperty(Document.prototype, 'onmouseenter', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseenter"].get, "get onmouseenter");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseenter"].set, "set onmouseenter");
sandbox_vm2.defineProperty(Document.prototype, 'onmouseleave', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseleave"].get, "get onmouseleave");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseleave"].set, "set onmouseleave");
sandbox_vm2.defineProperty(Document.prototype, 'onmousemove', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmousemove"].get, "get onmousemove");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmousemove"].set, "set onmousemove");
sandbox_vm2.defineProperty(Document.prototype, 'onmouseout', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseout"].get, "get onmouseout");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseout"].set, "set onmouseout");
sandbox_vm2.defineProperty(Document.prototype, 'onmouseover', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseover"].get, "get onmouseover");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseover"].set, "set onmouseover");
sandbox_vm2.defineProperty(Document.prototype, 'onmouseup', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseup"].get, "get onmouseup");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseup"].set, "set onmouseup");
sandbox_vm2.defineProperty(Document.prototype, 'onmousewheel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmousewheel"].get, "get onmousewheel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onmousewheel"].set, "set onmousewheel");
sandbox_vm2.defineProperty(Document.prototype, 'onpause', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpause"].get, "get onpause");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpause"].set, "set onpause");
sandbox_vm2.defineProperty(Document.prototype, 'onplay', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onplay"].get, "get onplay");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onplay"].set, "set onplay");
sandbox_vm2.defineProperty(Document.prototype, 'onplaying', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onplaying"].get, "get onplaying");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onplaying"].set, "set onplaying");
sandbox_vm2.defineProperty(Document.prototype, 'onprogress', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onprogress"].get, "get onprogress");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onprogress"].set, "set onprogress");
sandbox_vm2.defineProperty(Document.prototype, 'onratechange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onratechange"].get, "get onratechange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onratechange"].set, "set onratechange");
sandbox_vm2.defineProperty(Document.prototype, 'onreset', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onreset"].get, "get onreset");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onreset"].set, "set onreset");
sandbox_vm2.defineProperty(Document.prototype, 'onresize', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onresize"].get, "get onresize");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onresize"].set, "set onresize");
sandbox_vm2.defineProperty(Document.prototype, 'onscroll', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onscroll"].get, "get onscroll");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onscroll"].set, "set onscroll");
sandbox_vm2.defineProperty(Document.prototype, 'onsecuritypolicyviolation', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onsecuritypolicyviolation"].get, "get onsecuritypolicyviolation");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onsecuritypolicyviolation"].set, "set onsecuritypolicyviolation");
sandbox_vm2.defineProperty(Document.prototype, 'onseeked', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onseeked"].get, "get onseeked");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onseeked"].set, "set onseeked");
sandbox_vm2.defineProperty(Document.prototype, 'onseeking', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onseeking"].get, "get onseeking");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onseeking"].set, "set onseeking");
sandbox_vm2.defineProperty(Document.prototype, 'onselect', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onselect"].get, "get onselect");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onselect"].set, "set onselect");
sandbox_vm2.defineProperty(Document.prototype, 'onslotchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onslotchange"].get, "get onslotchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onslotchange"].set, "set onslotchange");
sandbox_vm2.defineProperty(Document.prototype, 'onstalled', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onstalled"].get, "get onstalled");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onstalled"].set, "set onstalled");
sandbox_vm2.defineProperty(Document.prototype, 'onsubmit', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onsubmit"].get, "get onsubmit");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onsubmit"].set, "set onsubmit");
sandbox_vm2.defineProperty(Document.prototype, 'onsuspend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onsuspend"].get, "get onsuspend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onsuspend"].set, "set onsuspend");
sandbox_vm2.defineProperty(Document.prototype, 'ontimeupdate', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontimeupdate"].get, "get ontimeupdate");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontimeupdate"].set, "set ontimeupdate");
sandbox_vm2.defineProperty(Document.prototype, 'ontoggle', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontoggle"].get, "get ontoggle");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontoggle"].set, "set ontoggle");
sandbox_vm2.defineProperty(Document.prototype, 'onvolumechange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onvolumechange"].get, "get onvolumechange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onvolumechange"].set, "set onvolumechange");
sandbox_vm2.defineProperty(Document.prototype, 'onwaiting', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwaiting"].get, "get onwaiting");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwaiting"].set, "set onwaiting");
sandbox_vm2.defineProperty(Document.prototype, 'onwebkitanimationend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationend"].get, "get onwebkitanimationend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationend"].set, "set onwebkitanimationend");
sandbox_vm2.defineProperty(Document.prototype, 'onwebkitanimationiteration', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationiteration"].get, "get onwebkitanimationiteration");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationiteration"].set, "set onwebkitanimationiteration");
sandbox_vm2.defineProperty(Document.prototype, 'onwebkitanimationstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationstart"].get, "get onwebkitanimationstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationstart"].set, "set onwebkitanimationstart");
sandbox_vm2.defineProperty(Document.prototype, 'onwebkittransitionend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkittransitionend"].get, "get onwebkittransitionend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkittransitionend"].set, "set onwebkittransitionend");
sandbox_vm2.defineProperty(Document.prototype, 'onwheel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwheel"].get, "get onwheel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onwheel"].set, "set onwheel");
sandbox_vm2.defineProperty(Document.prototype, 'onauxclick', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onauxclick"].get, "get onauxclick");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onauxclick"].set, "set onauxclick");
sandbox_vm2.defineProperty(Document.prototype, 'ongotpointercapture', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ongotpointercapture"].get, "get ongotpointercapture");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ongotpointercapture"].set, "set ongotpointercapture");
sandbox_vm2.defineProperty(Document.prototype, 'onlostpointercapture', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onlostpointercapture"].get, "get onlostpointercapture");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onlostpointercapture"].set, "set onlostpointercapture");
sandbox_vm2.defineProperty(Document.prototype, 'onpointerdown', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerdown"].get, "get onpointerdown");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerdown"].set, "set onpointerdown");
sandbox_vm2.defineProperty(Document.prototype, 'onpointermove', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointermove"].get, "get onpointermove");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointermove"].set, "set onpointermove");
sandbox_vm2.defineProperty(Document.prototype, 'onpointerrawupdate', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerrawupdate"].get, "get onpointerrawupdate");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerrawupdate"].set, "set onpointerrawupdate");
sandbox_vm2.defineProperty(Document.prototype, 'onpointerup', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerup"].get, "get onpointerup");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerup"].set, "set onpointerup");
sandbox_vm2.defineProperty(Document.prototype, 'onpointercancel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointercancel"].get, "get onpointercancel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointercancel"].set, "set onpointercancel");
sandbox_vm2.defineProperty(Document.prototype, 'onpointerover', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerover"].get, "get onpointerover");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerover"].set, "set onpointerover");
sandbox_vm2.defineProperty(Document.prototype, 'onpointerout', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerout"].get, "get onpointerout");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerout"].set, "set onpointerout");
sandbox_vm2.defineProperty(Document.prototype, 'onpointerenter', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerenter"].get, "get onpointerenter");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerenter"].set, "set onpointerenter");
sandbox_vm2.defineProperty(Document.prototype, 'onpointerleave', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerleave"].get, "get onpointerleave");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerleave"].set, "set onpointerleave");
sandbox_vm2.defineProperty(Document.prototype, 'onselectstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onselectstart"].get, "get onselectstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onselectstart"].set, "set onselectstart");
sandbox_vm2.defineProperty(Document.prototype, 'onselectionchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onselectionchange"].get, "get onselectionchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onselectionchange"].set, "set onselectionchange");
sandbox_vm2.defineProperty(Document.prototype, 'onanimationend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationend"].get, "get onanimationend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationend"].set, "set onanimationend");
sandbox_vm2.defineProperty(Document.prototype, 'onanimationiteration', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationiteration"].get, "get onanimationiteration");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationiteration"].set, "set onanimationiteration");
sandbox_vm2.defineProperty(Document.prototype, 'onanimationstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationstart"].get, "get onanimationstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationstart"].set, "set onanimationstart");
sandbox_vm2.defineProperty(Document.prototype, 'ontransitionrun', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionrun"].get, "get ontransitionrun");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionrun"].set, "set ontransitionrun");
sandbox_vm2.defineProperty(Document.prototype, 'ontransitionstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionstart"].get, "get ontransitionstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionstart"].set, "set ontransitionstart");
sandbox_vm2.defineProperty(Document.prototype, 'ontransitionend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionend"].get, "get ontransitionend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionend"].set, "set ontransitionend");
sandbox_vm2.defineProperty(Document.prototype, 'ontransitioncancel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitioncancel"].get, "get ontransitioncancel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitioncancel"].set, "set ontransitioncancel");
sandbox_vm2.defineProperty(Document.prototype, 'oncopy', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncopy"].get, "get oncopy");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncopy"].set, "set oncopy");
sandbox_vm2.defineProperty(Document.prototype, 'oncut', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncut"].get, "get oncut");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncut"].set, "set oncut");
sandbox_vm2.defineProperty(Document.prototype, 'onpaste', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpaste"].get, "get onpaste");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onpaste"].set, "set onpaste");
sandbox_vm2.defineProperty(Document.prototype, 'children', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["children"].get, "get children");
sandbox_vm2.defineProperty(Document.prototype, 'firstElementChild', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["firstElementChild"].get, "get firstElementChild");
sandbox_vm2.defineProperty(Document.prototype, 'lastElementChild', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["lastElementChild"].get, "get lastElementChild");
sandbox_vm2.defineProperty(Document.prototype, 'childElementCount', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["childElementCount"].get, "get childElementCount");
sandbox_vm2.defineProperty(Document.prototype, 'activeElement', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["activeElement"].get, "get activeElement");
sandbox_vm2.defineProperty(Document.prototype, 'styleSheets', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["styleSheets"].get, "get styleSheets");
sandbox_vm2.defineProperty(Document.prototype, 'pointerLockElement', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["pointerLockElement"].get, "get pointerLockElement");
sandbox_vm2.defineProperty(Document.prototype, 'fullscreenElement', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreenElement"].get, "get fullscreenElement");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreenElement"].set, "set fullscreenElement");
sandbox_vm2.defineProperty(Document.prototype, 'adoptedStyleSheets', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["adoptedStyleSheets"].get, "get adoptedStyleSheets");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["adoptedStyleSheets"].set, "set adoptedStyleSheets");
sandbox_vm2.defineProperty(Document.prototype, 'fonts', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["fonts"].get, "get fonts");
sandbox_vm2.defineProperty(Document.prototype, 'adoptNode', function adoptNode(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.adoptNode)
sandbox_vm2.defineProperty(Document.prototype, 'append', function append(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.append)
sandbox_vm2.defineProperty(Document.prototype, 'captureEvents', function captureEvents(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.captureEvents)
sandbox_vm2.defineProperty(Document.prototype, 'caretRangeFromPoint', function caretRangeFromPoint(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.caretRangeFromPoint)
sandbox_vm2.defineProperty(Document.prototype, 'clear', function clear(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.clear)
sandbox_vm2.defineProperty(Document.prototype, 'close', function close(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.close)
sandbox_vm2.defineProperty(Document.prototype, 'createAttribute', function createAttribute(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createAttribute)
sandbox_vm2.defineProperty(Document.prototype, 'createAttributeNS', function createAttributeNS(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createAttributeNS)
sandbox_vm2.defineProperty(Document.prototype, 'createCDATASection', function createCDATASection(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createCDATASection)
sandbox_vm2.defineProperty(Document.prototype, 'createComment', function createComment(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createComment)
sandbox_vm2.defineProperty(Document.prototype, 'createDocumentFragment', function createDocumentFragment(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createDocumentFragment)
sandbox_vm2.defineProperty(Document.prototype, 'createElement', function createElement(tagName){

    // let ele = `<${tagName}></${tagName}>`; 
    let ele = {}
    if (tagName === 'div'){
        Object.setPrototypeOf(ele, HTMLDivElement.prototype);
    }else if(tagName === 'canvas'){
        Object.setPrototypeOf(ele, HTMLCanvasElement.prototype);
    }else if(tagName === 'i'){
        Object.setPrototypeOf(ele, HTMLElement.prototype);
    }else{
        debugger;
        Object.setPrototypeOf(ele, HTMLUnknownElement.prototype);
    }


    // 存入内存 dom
    if (!sandbox_vm2.memory.dom?.tagName){
        sandbox_vm2.memory.dom.tagName = [];
    }

    // 标签属性
    ele.__index = sandbox_vm2.memory.dom.tagName.length;
    ele.__tagName = tagName;

    sandbox_vm2.memory.dom.tagName.push(ele);

    return ele

}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createElement)
sandbox_vm2.defineProperty(Document.prototype, 'createElementNS', function createElementNS(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createElementNS)
sandbox_vm2.defineProperty(Document.prototype, 'createEvent', function createEvent(type){
    let type_list = [
        "UIEvents",
        "MouseEvents",
        "MutationEvents",
        "HTMLEvents",
        "UIEvent",
        "MouseEvent",
        "MutationEvent",
        "MutationNameEvent",
        "TextEvent",
        "TextEvents",
        "KeyboardEvent",
        "KeyEvents",
        "CustomEvent",
        "Event",
        "Events",
        "SVGEvents",
        "SVGEvent",
        "SVGZoomEvents",
        "SVGZoomEvent",
        "MessageEvent",
        "MouseScrollEvents",
        "PopupEvents",
        "PopupBlockedEvents",
        "XULCommandEvent",
        "XULCommandEvents",
        "ProgressEvent",
        "AnimationEvent",
        "WebKitAnimationEvent",
        "TransitionEvent",
        "WebKitTransitionEvent",
    ]
    // if (type_list.indexOf(type) == -1){
    //     let e = new Error(`createEvent 事件类型错误. ${type} `)
    //     throw e;
    // }

    let e = new Event(type);
    return e;

}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createEvent)
sandbox_vm2.defineProperty(Document.prototype, 'createExpression', function createExpression(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createExpression)
sandbox_vm2.defineProperty(Document.prototype, 'createNSResolver', function createNSResolver(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createNSResolver)
sandbox_vm2.defineProperty(Document.prototype, 'createNodeIterator', function createNodeIterator(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createNodeIterator)
sandbox_vm2.defineProperty(Document.prototype, 'createProcessingInstruction', function createProcessingInstruction(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createProcessingInstruction)
sandbox_vm2.defineProperty(Document.prototype, 'createRange', function createRange(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createRange)
sandbox_vm2.defineProperty(Document.prototype, 'createTextNode', function createTextNode(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createTextNode)
sandbox_vm2.defineProperty(Document.prototype, 'createTreeWalker', function createTreeWalker(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.createTreeWalker)
sandbox_vm2.defineProperty(Document.prototype, 'elementFromPoint', function elementFromPoint(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.elementFromPoint)
sandbox_vm2.defineProperty(Document.prototype, 'elementsFromPoint', function elementsFromPoint(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.elementsFromPoint)
sandbox_vm2.defineProperty(Document.prototype, 'evaluate', function evaluate(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.evaluate)
sandbox_vm2.defineProperty(Document.prototype, 'execCommand', function execCommand(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.execCommand)
sandbox_vm2.defineProperty(Document.prototype, 'exitFullscreen', function exitFullscreen(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.exitFullscreen)
sandbox_vm2.defineProperty(Document.prototype, 'exitPictureInPicture', function exitPictureInPicture(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.exitPictureInPicture)
sandbox_vm2.defineProperty(Document.prototype, 'exitPointerLock', function exitPointerLock(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.exitPointerLock)
sandbox_vm2.defineProperty(Document.prototype, 'getElementById', function getElementById(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.getElementById)
sandbox_vm2.defineProperty(Document.prototype, 'getElementsByClassName', function getElementsByClassName(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.getElementsByClassName)
sandbox_vm2.defineProperty(Document.prototype, 'getElementsByName', function getElementsByName(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.getElementsByName)
sandbox_vm2.defineProperty(Document.prototype, 'getElementsByTagName', function getElementsByTagName(tagName){
    let eles = []
    
    if (sandbox_vm2.memory.dom?.tagName){
        eles = sandbox_vm2.memory.dom.tagName;
    }

    Object.setPrototypeOf(eles, HTMLCollection.prototype);

    return eles;
}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.getElementsByTagName)
sandbox_vm2.defineProperty(Document.prototype, 'getElementsByTagNameNS', function getElementsByTagNameNS(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.getElementsByTagNameNS)
sandbox_vm2.defineProperty(Document.prototype, 'getSelection', function getSelection(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.getSelection)
sandbox_vm2.defineProperty(Document.prototype, 'hasFocus', function hasFocus(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.hasFocus)
sandbox_vm2.defineProperty(Document.prototype, 'importNode', function importNode(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.importNode)
sandbox_vm2.defineProperty(Document.prototype, 'open', function open(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.open)
sandbox_vm2.defineProperty(Document.prototype, 'prepend', function prepend(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.prepend)
sandbox_vm2.defineProperty(Document.prototype, 'queryCommandEnabled', function queryCommandEnabled(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.queryCommandEnabled)
sandbox_vm2.defineProperty(Document.prototype, 'queryCommandIndeterm', function queryCommandIndeterm(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.queryCommandIndeterm)
sandbox_vm2.defineProperty(Document.prototype, 'queryCommandState', function queryCommandState(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.queryCommandState)
sandbox_vm2.defineProperty(Document.prototype, 'queryCommandSupported', function queryCommandSupported(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.queryCommandSupported)
sandbox_vm2.defineProperty(Document.prototype, 'queryCommandValue', function queryCommandValue(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.queryCommandValue)
sandbox_vm2.defineProperty(Document.prototype, 'querySelector', function querySelector(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.querySelector)
sandbox_vm2.defineProperty(Document.prototype, 'querySelectorAll', function querySelectorAll(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.querySelectorAll)
sandbox_vm2.defineProperty(Document.prototype, 'releaseEvents', function releaseEvents(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.releaseEvents)
sandbox_vm2.defineProperty(Document.prototype, 'replaceChildren', function replaceChildren(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.replaceChildren)
sandbox_vm2.defineProperty(Document.prototype, 'webkitCancelFullScreen', function webkitCancelFullScreen(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.webkitCancelFullScreen)
sandbox_vm2.defineProperty(Document.prototype, 'webkitExitFullscreen', function webkitExitFullscreen(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.webkitExitFullscreen)
sandbox_vm2.defineProperty(Document.prototype, 'write', function write(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.write)
sandbox_vm2.defineProperty(Document.prototype, 'writeln', function writeln(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.writeln)

sandbox_vm2.defineProperty(Document.prototype, 'prerendering', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["prerendering"].get, "get prerendering");
sandbox_vm2.defineProperty(Document.prototype, 'onprerenderingchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onprerenderingchange"].get, "get onprerenderingchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onprerenderingchange"].set, "set onprerenderingchange");
sandbox_vm2.defineProperty(Document.prototype, 'fragmentDirective', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["fragmentDirective"].get, "get fragmentDirective");
sandbox_vm2.defineProperty(Document.prototype, 'onbeforematch', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforematch"].get, "get onbeforematch");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforematch"].set, "set onbeforematch");
sandbox_vm2.defineProperty(Document.prototype, 'timeline', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["timeline"].get, "get timeline");
sandbox_vm2.defineProperty(Document.prototype, 'oncontentvisibilityautostatechange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncontentvisibilityautostatechange"].get, "get oncontentvisibilityautostatechange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Document.prototype)["oncontentvisibilityautostatechange"].set, "set oncontentvisibilityautostatechange");
sandbox_vm2.defineProperty(Document.prototype, 'getAnimations', function getAnimations(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.getAnimations)
sandbox_vm2.defineProperty(Document.prototype, 'startViewTransition', function startViewTransition(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Document.prototype.startViewTransition)
