Element = function Element(){
    sandbox_vm2.throwError("TypeError", "Illegal constructor") 
}
sandbox_vm2.func_set_native(Element)
sandbox_vm2.rename(Element.prototype, "Element")

Object.setPrototypeOf(Element.prototype,Node.prototype)
sandbox_vm2.defineProperty(Element.prototype, 'namespaceURI', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["namespaceURI"].get, "get namespaceURI");
sandbox_vm2.defineProperty(Element.prototype, 'prefix', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["prefix"].get, "get prefix");
sandbox_vm2.defineProperty(Element.prototype, 'localName', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["localName"].get, "get localName");
sandbox_vm2.defineProperty(Element.prototype, 'tagName', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["tagName"].get, "get tagName");
sandbox_vm2.defineProperty(Element.prototype, 'id', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["id"].get, "get id");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["id"].set, "set id");
sandbox_vm2.defineProperty(Element.prototype, 'className', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["className"].get, "get className");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["className"].set, "set className");
sandbox_vm2.defineProperty(Element.prototype, 'classList', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["classList"].get, "get classList");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["classList"].set, "set classList");
sandbox_vm2.defineProperty(Element.prototype, 'slot', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["slot"].get, "get slot");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["slot"].set, "set slot");
sandbox_vm2.defineProperty(Element.prototype, 'attributes', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["attributes"].get, "get attributes");
sandbox_vm2.defineProperty(Element.prototype, 'shadowRoot', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["shadowRoot"].get, "get shadowRoot");
sandbox_vm2.defineProperty(Element.prototype, 'part', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["part"].get, "get part");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["part"].set, "set part");
sandbox_vm2.defineProperty(Element.prototype, 'assignedSlot', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["assignedSlot"].get, "get assignedSlot");
sandbox_vm2.defineProperty(Element.prototype, 'innerHTML', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["innerHTML"].get, "get innerHTML");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["innerHTML"].set, "set innerHTML");
sandbox_vm2.defineProperty(Element.prototype, 'outerHTML', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["outerHTML"].get, "get outerHTML");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["outerHTML"].set, "set outerHTML");
sandbox_vm2.defineProperty(Element.prototype, 'scrollTop', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["scrollTop"].get, "get scrollTop");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["scrollTop"].set, "set scrollTop");
sandbox_vm2.defineProperty(Element.prototype, 'scrollLeft', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["scrollLeft"].get, "get scrollLeft");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["scrollLeft"].set, "set scrollLeft");
sandbox_vm2.defineProperty(Element.prototype, 'scrollWidth', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["scrollWidth"].get, "get scrollWidth");
sandbox_vm2.defineProperty(Element.prototype, 'scrollHeight', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["scrollHeight"].get, "get scrollHeight");
sandbox_vm2.defineProperty(Element.prototype, 'clientTop', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["clientTop"].get, "get clientTop");
sandbox_vm2.defineProperty(Element.prototype, 'clientLeft', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["clientLeft"].get, "get clientLeft");
sandbox_vm2.defineProperty(Element.prototype, 'clientWidth', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["clientWidth"].get, "get clientWidth");
sandbox_vm2.defineProperty(Element.prototype, 'clientHeight', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["clientHeight"].get, "get clientHeight");
sandbox_vm2.defineProperty(Element.prototype, 'attributeStyleMap', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["attributeStyleMap"].get, "get attributeStyleMap");
sandbox_vm2.defineProperty(Element.prototype, 'onbeforecopy', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onbeforecopy"].get, "get onbeforecopy");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onbeforecopy"].set, "set onbeforecopy");
sandbox_vm2.defineProperty(Element.prototype, 'onbeforecut', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onbeforecut"].get, "get onbeforecut");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onbeforecut"].set, "set onbeforecut");
sandbox_vm2.defineProperty(Element.prototype, 'onbeforepaste', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onbeforepaste"].get, "get onbeforepaste");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onbeforepaste"].set, "set onbeforepaste");
sandbox_vm2.defineProperty(Element.prototype, 'onsearch', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onsearch"].get, "get onsearch");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onsearch"].set, "set onsearch");
sandbox_vm2.defineProperty(Element.prototype, 'elementTiming', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["elementTiming"].get, "get elementTiming");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["elementTiming"].set, "set elementTiming");
sandbox_vm2.defineProperty(Element.prototype, 'onfullscreenchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onfullscreenchange"].get, "get onfullscreenchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onfullscreenchange"].set, "set onfullscreenchange");
sandbox_vm2.defineProperty(Element.prototype, 'onfullscreenerror', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onfullscreenerror"].get, "get onfullscreenerror");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onfullscreenerror"].set, "set onfullscreenerror");
sandbox_vm2.defineProperty(Element.prototype, 'onwebkitfullscreenchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onwebkitfullscreenchange"].get, "get onwebkitfullscreenchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onwebkitfullscreenchange"].set, "set onwebkitfullscreenchange");
sandbox_vm2.defineProperty(Element.prototype, 'onwebkitfullscreenerror', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onwebkitfullscreenerror"].get, "get onwebkitfullscreenerror");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["onwebkitfullscreenerror"].set, "set onwebkitfullscreenerror");
sandbox_vm2.defineProperty(Element.prototype, 'role', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["role"].get, "get role");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["role"].set, "set role");
sandbox_vm2.defineProperty(Element.prototype, 'ariaAtomic', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaAtomic"].get, "get ariaAtomic");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaAtomic"].set, "set ariaAtomic");
sandbox_vm2.defineProperty(Element.prototype, 'ariaAutoComplete', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaAutoComplete"].get, "get ariaAutoComplete");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaAutoComplete"].set, "set ariaAutoComplete");
sandbox_vm2.defineProperty(Element.prototype, 'ariaBusy', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaBusy"].get, "get ariaBusy");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaBusy"].set, "set ariaBusy");
sandbox_vm2.defineProperty(Element.prototype, 'ariaChecked', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaChecked"].get, "get ariaChecked");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaChecked"].set, "set ariaChecked");
sandbox_vm2.defineProperty(Element.prototype, 'ariaColCount', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaColCount"].get, "get ariaColCount");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaColCount"].set, "set ariaColCount");
sandbox_vm2.defineProperty(Element.prototype, 'ariaColIndex', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaColIndex"].get, "get ariaColIndex");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaColIndex"].set, "set ariaColIndex");
sandbox_vm2.defineProperty(Element.prototype, 'ariaColSpan', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaColSpan"].get, "get ariaColSpan");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaColSpan"].set, "set ariaColSpan");
sandbox_vm2.defineProperty(Element.prototype, 'ariaCurrent', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaCurrent"].get, "get ariaCurrent");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaCurrent"].set, "set ariaCurrent");
sandbox_vm2.defineProperty(Element.prototype, 'ariaDescription', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaDescription"].get, "get ariaDescription");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaDescription"].set, "set ariaDescription");
sandbox_vm2.defineProperty(Element.prototype, 'ariaDisabled', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaDisabled"].get, "get ariaDisabled");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaDisabled"].set, "set ariaDisabled");
sandbox_vm2.defineProperty(Element.prototype, 'ariaExpanded', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaExpanded"].get, "get ariaExpanded");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaExpanded"].set, "set ariaExpanded");
sandbox_vm2.defineProperty(Element.prototype, 'ariaHasPopup', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaHasPopup"].get, "get ariaHasPopup");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaHasPopup"].set, "set ariaHasPopup");
sandbox_vm2.defineProperty(Element.prototype, 'ariaHidden', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaHidden"].get, "get ariaHidden");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaHidden"].set, "set ariaHidden");
sandbox_vm2.defineProperty(Element.prototype, 'ariaInvalid', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaInvalid"].get, "get ariaInvalid");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaInvalid"].set, "set ariaInvalid");
sandbox_vm2.defineProperty(Element.prototype, 'ariaKeyShortcuts', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaKeyShortcuts"].get, "get ariaKeyShortcuts");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaKeyShortcuts"].set, "set ariaKeyShortcuts");
sandbox_vm2.defineProperty(Element.prototype, 'ariaLabel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaLabel"].get, "get ariaLabel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaLabel"].set, "set ariaLabel");
sandbox_vm2.defineProperty(Element.prototype, 'ariaLevel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaLevel"].get, "get ariaLevel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaLevel"].set, "set ariaLevel");
sandbox_vm2.defineProperty(Element.prototype, 'ariaLive', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaLive"].get, "get ariaLive");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaLive"].set, "set ariaLive");
sandbox_vm2.defineProperty(Element.prototype, 'ariaModal', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaModal"].get, "get ariaModal");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaModal"].set, "set ariaModal");
sandbox_vm2.defineProperty(Element.prototype, 'ariaMultiLine', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaMultiLine"].get, "get ariaMultiLine");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaMultiLine"].set, "set ariaMultiLine");
sandbox_vm2.defineProperty(Element.prototype, 'ariaMultiSelectable', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaMultiSelectable"].get, "get ariaMultiSelectable");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaMultiSelectable"].set, "set ariaMultiSelectable");
sandbox_vm2.defineProperty(Element.prototype, 'ariaOrientation', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaOrientation"].get, "get ariaOrientation");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaOrientation"].set, "set ariaOrientation");
sandbox_vm2.defineProperty(Element.prototype, 'ariaPlaceholder', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaPlaceholder"].get, "get ariaPlaceholder");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaPlaceholder"].set, "set ariaPlaceholder");
sandbox_vm2.defineProperty(Element.prototype, 'ariaPosInSet', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaPosInSet"].get, "get ariaPosInSet");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaPosInSet"].set, "set ariaPosInSet");
sandbox_vm2.defineProperty(Element.prototype, 'ariaPressed', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaPressed"].get, "get ariaPressed");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaPressed"].set, "set ariaPressed");
sandbox_vm2.defineProperty(Element.prototype, 'ariaReadOnly', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaReadOnly"].get, "get ariaReadOnly");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaReadOnly"].set, "set ariaReadOnly");
sandbox_vm2.defineProperty(Element.prototype, 'ariaRelevant', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRelevant"].get, "get ariaRelevant");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRelevant"].set, "set ariaRelevant");
sandbox_vm2.defineProperty(Element.prototype, 'ariaRequired', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRequired"].get, "get ariaRequired");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRequired"].set, "set ariaRequired");
sandbox_vm2.defineProperty(Element.prototype, 'ariaRoleDescription', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRoleDescription"].get, "get ariaRoleDescription");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRoleDescription"].set, "set ariaRoleDescription");
sandbox_vm2.defineProperty(Element.prototype, 'ariaRowCount', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRowCount"].get, "get ariaRowCount");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRowCount"].set, "set ariaRowCount");
sandbox_vm2.defineProperty(Element.prototype, 'ariaRowIndex', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRowIndex"].get, "get ariaRowIndex");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRowIndex"].set, "set ariaRowIndex");
sandbox_vm2.defineProperty(Element.prototype, 'ariaRowSpan', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRowSpan"].get, "get ariaRowSpan");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaRowSpan"].set, "set ariaRowSpan");
sandbox_vm2.defineProperty(Element.prototype, 'ariaSelected', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaSelected"].get, "get ariaSelected");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaSelected"].set, "set ariaSelected");
sandbox_vm2.defineProperty(Element.prototype, 'ariaSetSize', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaSetSize"].get, "get ariaSetSize");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaSetSize"].set, "set ariaSetSize");
sandbox_vm2.defineProperty(Element.prototype, 'ariaSort', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaSort"].get, "get ariaSort");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaSort"].set, "set ariaSort");
sandbox_vm2.defineProperty(Element.prototype, 'ariaValueMax', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaValueMax"].get, "get ariaValueMax");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaValueMax"].set, "set ariaValueMax");
sandbox_vm2.defineProperty(Element.prototype, 'ariaValueMin', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaValueMin"].get, "get ariaValueMin");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaValueMin"].set, "set ariaValueMin");
sandbox_vm2.defineProperty(Element.prototype, 'ariaValueNow', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaValueNow"].get, "get ariaValueNow");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaValueNow"].set, "set ariaValueNow");
sandbox_vm2.defineProperty(Element.prototype, 'ariaValueText', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaValueText"].get, "get ariaValueText");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["ariaValueText"].set, "set ariaValueText");
sandbox_vm2.defineProperty(Element.prototype, 'children', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["children"].get, "get children");
sandbox_vm2.defineProperty(Element.prototype, 'firstElementChild', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["firstElementChild"].get, "get firstElementChild");
sandbox_vm2.defineProperty(Element.prototype, 'lastElementChild', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["lastElementChild"].get, "get lastElementChild");
sandbox_vm2.defineProperty(Element.prototype, 'childElementCount', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["childElementCount"].get, "get childElementCount");
sandbox_vm2.defineProperty(Element.prototype, 'previousElementSibling', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["previousElementSibling"].get, "get previousElementSibling");
sandbox_vm2.defineProperty(Element.prototype, 'nextElementSibling', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(Element.prototype)["nextElementSibling"].get, "get nextElementSibling");
sandbox_vm2.defineProperty(Element.prototype, 'after', function after(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.after)
sandbox_vm2.defineProperty(Element.prototype, 'animate', function animate(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.animate)
sandbox_vm2.defineProperty(Element.prototype, 'append', function append(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.append)
sandbox_vm2.defineProperty(Element.prototype, 'attachShadow', function attachShadow(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.attachShadow)
sandbox_vm2.defineProperty(Element.prototype, 'before', function before(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.before)
sandbox_vm2.defineProperty(Element.prototype, 'closest', function closest(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.closest)
sandbox_vm2.defineProperty(Element.prototype, 'computedStyleMap', function computedStyleMap(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.computedStyleMap)
sandbox_vm2.defineProperty(Element.prototype, 'getAttribute', function getAttribute(attributeName){
    return this.attributeName;
}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getAttribute)
sandbox_vm2.defineProperty(Element.prototype, 'getAttributeNS', function getAttributeNS(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getAttributeNS)
sandbox_vm2.defineProperty(Element.prototype, 'getAttributeNames', function getAttributeNames(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getAttributeNames)
sandbox_vm2.defineProperty(Element.prototype, 'getAttributeNode', function getAttributeNode(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getAttributeNode)
sandbox_vm2.defineProperty(Element.prototype, 'getAttributeNodeNS', function getAttributeNodeNS(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getAttributeNodeNS)
sandbox_vm2.defineProperty(Element.prototype, 'getBoundingClientRect', function getBoundingClientRect(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getBoundingClientRect)
sandbox_vm2.defineProperty(Element.prototype, 'getClientRects', function getClientRects(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getClientRects)
sandbox_vm2.defineProperty(Element.prototype, 'getElementsByClassName', function getElementsByClassName(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getElementsByClassName)
sandbox_vm2.defineProperty(Element.prototype, 'getElementsByTagName', function getElementsByTagName(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getElementsByTagName)
sandbox_vm2.defineProperty(Element.prototype, 'getElementsByTagNameNS', function getElementsByTagNameNS(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getElementsByTagNameNS)
sandbox_vm2.defineProperty(Element.prototype, 'getInnerHTML', function getInnerHTML(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getInnerHTML)
sandbox_vm2.defineProperty(Element.prototype, 'hasAttribute', function hasAttribute(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.hasAttribute)
sandbox_vm2.defineProperty(Element.prototype, 'hasAttributeNS', function hasAttributeNS(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.hasAttributeNS)
sandbox_vm2.defineProperty(Element.prototype, 'hasAttributes', function hasAttributes(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.hasAttributes)
sandbox_vm2.defineProperty(Element.prototype, 'hasPointerCapture', function hasPointerCapture(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.hasPointerCapture)
sandbox_vm2.defineProperty(Element.prototype, 'insertAdjacentElement', function insertAdjacentElement(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.insertAdjacentElement)
sandbox_vm2.defineProperty(Element.prototype, 'insertAdjacentHTML', function insertAdjacentHTML(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.insertAdjacentHTML)
sandbox_vm2.defineProperty(Element.prototype, 'insertAdjacentText', function insertAdjacentText(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.insertAdjacentText)
sandbox_vm2.defineProperty(Element.prototype, 'matches', function matches(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.matches)
sandbox_vm2.defineProperty(Element.prototype, 'prepend', function prepend(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.prepend)
sandbox_vm2.defineProperty(Element.prototype, 'querySelector', function querySelector(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.querySelector)
sandbox_vm2.defineProperty(Element.prototype, 'querySelectorAll', function querySelectorAll(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.querySelectorAll)
sandbox_vm2.defineProperty(Element.prototype, 'releasePointerCapture', function releasePointerCapture(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.releasePointerCapture)
sandbox_vm2.defineProperty(Element.prototype, 'remove', function remove(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.remove)
sandbox_vm2.defineProperty(Element.prototype, 'removeAttribute', function removeAttribute(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.removeAttribute)
sandbox_vm2.defineProperty(Element.prototype, 'removeAttributeNS', function removeAttributeNS(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.removeAttributeNS)
sandbox_vm2.defineProperty(Element.prototype, 'removeAttributeNode', function removeAttributeNode(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.removeAttributeNode)
sandbox_vm2.defineProperty(Element.prototype, 'replaceChildren', function replaceChildren(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.replaceChildren)
sandbox_vm2.defineProperty(Element.prototype, 'replaceWith', function replaceWith(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.replaceWith)
sandbox_vm2.defineProperty(Element.prototype, 'requestFullscreen', function requestFullscreen(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.requestFullscreen)
sandbox_vm2.defineProperty(Element.prototype, 'requestPointerLock', function requestPointerLock(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.requestPointerLock)
sandbox_vm2.defineProperty(Element.prototype, 'scroll', function scroll(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.scroll)
sandbox_vm2.defineProperty(Element.prototype, 'scrollBy', function scrollBy(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.scrollBy)
sandbox_vm2.defineProperty(Element.prototype, 'scrollIntoView', function scrollIntoView(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.scrollIntoView)
sandbox_vm2.defineProperty(Element.prototype, 'scrollIntoViewIfNeeded', function scrollIntoViewIfNeeded(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.scrollIntoViewIfNeeded)
sandbox_vm2.defineProperty(Element.prototype, 'scrollTo', function scrollTo(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.scrollTo)
sandbox_vm2.defineProperty(Element.prototype, 'setAttribute', function setAttribute(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.setAttribute)
sandbox_vm2.defineProperty(Element.prototype, 'setAttributeNS', function setAttributeNS(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.setAttributeNS)
sandbox_vm2.defineProperty(Element.prototype, 'setAttributeNode', function setAttributeNode(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.setAttributeNode)
sandbox_vm2.defineProperty(Element.prototype, 'setAttributeNodeNS', function setAttributeNodeNS(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.setAttributeNodeNS)
sandbox_vm2.defineProperty(Element.prototype, 'setPointerCapture', function setPointerCapture(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.setPointerCapture)
sandbox_vm2.defineProperty(Element.prototype, 'toggleAttribute', function toggleAttribute(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.toggleAttribute)
sandbox_vm2.defineProperty(Element.prototype, 'webkitMatchesSelector', function webkitMatchesSelector(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.webkitMatchesSelector)
sandbox_vm2.defineProperty(Element.prototype, 'webkitRequestFullScreen', function webkitRequestFullScreen(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.webkitRequestFullScreen)
sandbox_vm2.defineProperty(Element.prototype, 'webkitRequestFullscreen', function webkitRequestFullscreen(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.webkitRequestFullscreen)
sandbox_vm2.defineProperty(Element.prototype, 'getAnimations', function getAnimations(){debugger;}, true, true, true); sandbox_vm2.func_set_native(Element.prototype.getAnimations)
