HTMLScriptElement = function HTMLScriptElement(){
    sandbox_vm2.throwError("TypeError", "Illegal constructor") 
}
sandbox_vm2.func_set_native(HTMLScriptElement)
sandbox_vm2.rename(HTMLScriptElement.prototype, "HTMLScriptElement")

Object.setPrototypeOf(HTMLScriptElement.prototype,HTMLElement.prototype)
sandbox_vm2.defineProperty(HTMLScriptElement, 'supports', function supports(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLScriptElement.supports)
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'src', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["src"].get, "get src");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["src"].set, "set src");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'type', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["type"].get, "get type");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["type"].set, "set type");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'noModule', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["noModule"].get, "get noModule");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["noModule"].set, "set noModule");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'charset', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["charset"].get, "get charset");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["charset"].set, "set charset");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'async', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["async"].get, "get async");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["async"].set, "set async");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'defer', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["defer"].get, "get defer");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["defer"].set, "set defer");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'crossOrigin', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["crossOrigin"].get, "get crossOrigin");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["crossOrigin"].set, "set crossOrigin");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'text', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["text"].get, "get text");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["text"].set, "set text");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'referrerPolicy', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["referrerPolicy"].get, "get referrerPolicy");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["referrerPolicy"].set, "set referrerPolicy");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'event', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["event"].get, "get event");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["event"].set, "set event");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'htmlFor', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["htmlFor"].get, "get htmlFor");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["htmlFor"].set, "set htmlFor");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'integrity', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["integrity"].get, "get integrity");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["integrity"].set, "set integrity");
sandbox_vm2.defineProperty(HTMLScriptElement.prototype, 'fetchPriority', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["fetchPriority"].get, "get fetchPriority");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLScriptElement.prototype)["fetchPriority"].set, "set fetchPriority");
