HTMLMediaElement = function HTMLMediaElement(){
            sandbox_vm2.throwError("TypeError", "Illegal constructor")
}
sandbox_vm2.func_set_native(HTMLMediaElement)
sandbox_vm2.rename(HTMLMediaElement.prototype, "HTMLMediaElement")

Object.setPrototypeOf(HTMLMediaElement.prototype,HTMLElement.prototype)
sandbox_vm2.defineProperty(HTMLMediaElement, 'NETWORK_EMPTY', 0, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement, 'NETWORK_IDLE', 1, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement, 'NETWORK_LOADING', 2, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement, 'NETWORK_NO_SOURCE', 3, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement, 'HAVE_NOTHING', 0, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement, 'HAVE_METADATA', 1, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement, 'HAVE_CURRENT_DATA', 2, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement, 'HAVE_FUTURE_DATA', 3, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement, 'HAVE_ENOUGH_DATA', 4, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'error', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["error"].get, "get error");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'src', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["src"].get, "get src");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["src"].set, "set src");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'currentSrc', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["currentSrc"].get, "get currentSrc");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'crossOrigin', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["crossOrigin"].get, "get crossOrigin");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["crossOrigin"].set, "set crossOrigin");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'networkState', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["networkState"].get, "get networkState");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'preload', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["preload"].get, "get preload");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["preload"].set, "set preload");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'buffered', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["buffered"].get, "get buffered");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'readyState', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["readyState"].get, "get readyState");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'seeking', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["seeking"].get, "get seeking");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'currentTime', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["currentTime"].get, "get currentTime");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["currentTime"].set, "set currentTime");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'duration', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["duration"].get, "get duration");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'paused', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["paused"].get, "get paused");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'defaultPlaybackRate', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["defaultPlaybackRate"].get, "get defaultPlaybackRate");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["defaultPlaybackRate"].set, "set defaultPlaybackRate");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'playbackRate', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["playbackRate"].get, "get playbackRate");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["playbackRate"].set, "set playbackRate");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'played', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["played"].get, "get played");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'seekable', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["seekable"].get, "get seekable");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'ended', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["ended"].get, "get ended");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'autoplay', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["autoplay"].get, "get autoplay");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["autoplay"].set, "set autoplay");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'loop', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["loop"].get, "get loop");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["loop"].set, "set loop");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'preservesPitch', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["preservesPitch"].get, "get preservesPitch");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["preservesPitch"].set, "set preservesPitch");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'controls', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["controls"].get, "get controls");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["controls"].set, "set controls");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'controlsList', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["controlsList"].get, "get controlsList");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["controlsList"].set, "set controlsList");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'volume', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["volume"].get, "get volume");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["volume"].set, "set volume");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'muted', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["muted"].get, "get muted");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["muted"].set, "set muted");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'defaultMuted', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["defaultMuted"].get, "get defaultMuted");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["defaultMuted"].set, "set defaultMuted");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'textTracks', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["textTracks"].get, "get textTracks");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'webkitAudioDecodedByteCount', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["webkitAudioDecodedByteCount"].get, "get webkitAudioDecodedByteCount");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'webkitVideoDecodedByteCount', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["webkitVideoDecodedByteCount"].get, "get webkitVideoDecodedByteCount");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'onencrypted', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["onencrypted"].get, "get onencrypted");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["onencrypted"].set, "set onencrypted");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'onwaitingforkey', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["onwaitingforkey"].get, "get onwaitingforkey");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["onwaitingforkey"].set, "set onwaitingforkey");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'srcObject', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["srcObject"].get, "get srcObject");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["srcObject"].set, "set srcObject");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'NETWORK_EMPTY', 0, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'NETWORK_IDLE', 1, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'NETWORK_LOADING', 2, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'NETWORK_NO_SOURCE', 3, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'HAVE_NOTHING', 0, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'HAVE_METADATA', 1, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'HAVE_CURRENT_DATA', 2, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'HAVE_FUTURE_DATA', 3, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'HAVE_ENOUGH_DATA', 4, false, true, false);
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'addTextTrack', function addTextTrack(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLMediaElement.prototype.addTextTrack)
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'canPlayType', function canPlayType(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLMediaElement.prototype.canPlayType)
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'captureStream', function captureStream(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLMediaElement.prototype.captureStream)
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'load', function load(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLMediaElement.prototype.load)
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'pause', function pause(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLMediaElement.prototype.pause)
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'play', function play(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLMediaElement.prototype.play)
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'sinkId', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["sinkId"].get, "get sinkId");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'remote', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["remote"].get, "get remote");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'disableRemotePlayback', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["disableRemotePlayback"].get, "get disableRemotePlayback");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["disableRemotePlayback"].set, "set disableRemotePlayback");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'setSinkId', function setSinkId(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLMediaElement.prototype.setSinkId)

sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'mediaKeys', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLMediaElement.prototype)["mediaKeys"].get, "get mediaKeys");
sandbox_vm2.defineProperty(HTMLMediaElement.prototype, 'setMediaKeys', function setMediaKeys(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLMediaElement.prototype.setMediaKeys)
