HTMLElement = function HTMLElement(){
    sandbox_vm2.throwError("TypeError", "Illegal constructor") 
}
sandbox_vm2.func_set_native(HTMLElement) 
sandbox_vm2.rename(HTMLElement.prototype, "HTMLElement")

Object.setPrototypeOf(HTMLElement.prototype,Element.prototype)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'title', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["title"].get, "get title");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["title"].set, "set title");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'lang', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["lang"].get, "get lang");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["lang"].set, "set lang");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'translate', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["translate"].get, "get translate");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["translate"].set, "set translate");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'dir', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["dir"].get, "get dir");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["dir"].set, "set dir");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'hidden', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["hidden"].get, "get hidden");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["hidden"].set, "set hidden");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'accessKey', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["accessKey"].get, "get accessKey");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["accessKey"].set, "set accessKey");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'draggable', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["draggable"].get, "get draggable");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["draggable"].set, "set draggable");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'spellcheck', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["spellcheck"].get, "get spellcheck");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["spellcheck"].set, "set spellcheck");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'autocapitalize', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["autocapitalize"].get, "get autocapitalize");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["autocapitalize"].set, "set autocapitalize");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'contentEditable', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["contentEditable"].get, "get contentEditable");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["contentEditable"].set, "set contentEditable");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'isContentEditable', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["isContentEditable"].get, "get isContentEditable");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'inputMode', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["inputMode"].get, "get inputMode");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["inputMode"].set, "set inputMode");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'offsetParent', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["offsetParent"].get, "get offsetParent");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'offsetTop', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["offsetTop"].get, "get offsetTop");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'offsetLeft', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["offsetLeft"].get, "get offsetLeft");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'offsetWidth', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["offsetWidth"].get, "get offsetWidth");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'offsetHeight', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["offsetHeight"].get, "get offsetHeight");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'innerText', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["innerText"].get, "get innerText");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["innerText"].set, "set innerText");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'outerText', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["outerText"].get, "get outerText");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["outerText"].set, "set outerText");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onbeforexrselect', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onbeforexrselect"].get, "get onbeforexrselect");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onbeforexrselect"].set, "set onbeforexrselect");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onabort', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onabort"].get, "get onabort");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onabort"].set, "set onabort");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onblur', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onblur"].get, "get onblur");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onblur"].set, "set onblur");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncancel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncancel"].get, "get oncancel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncancel"].set, "set oncancel");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncanplay', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncanplay"].get, "get oncanplay");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncanplay"].set, "set oncanplay");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncanplaythrough', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncanplaythrough"].get, "get oncanplaythrough");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncanplaythrough"].set, "set oncanplaythrough");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onchange"].get, "get onchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onchange"].set, "set onchange");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onclick', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onclick"].get, "get onclick");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onclick"].set, "set onclick");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onclose', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onclose"].get, "get onclose");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onclose"].set, "set onclose");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncontextlost', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncontextlost"].get, "get oncontextlost");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncontextlost"].set, "set oncontextlost");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncontextmenu', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncontextmenu"].get, "get oncontextmenu");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncontextmenu"].set, "set oncontextmenu");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncontextrestored', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncontextrestored"].get, "get oncontextrestored");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncontextrestored"].set, "set oncontextrestored");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncuechange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncuechange"].get, "get oncuechange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncuechange"].set, "set oncuechange");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondblclick', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondblclick"].get, "get ondblclick");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondblclick"].set, "set ondblclick");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondrag', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondrag"].get, "get ondrag");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondrag"].set, "set ondrag");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondragend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondragend"].get, "get ondragend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondragend"].set, "set ondragend");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondragenter', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondragenter"].get, "get ondragenter");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondragenter"].set, "set ondragenter");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondragleave', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondragleave"].get, "get ondragleave");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondragleave"].set, "set ondragleave");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondragover', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondragover"].get, "get ondragover");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondragover"].set, "set ondragover");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondragstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondragstart"].get, "get ondragstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondragstart"].set, "set ondragstart");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondrop', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondrop"].get, "get ondrop");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondrop"].set, "set ondrop");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondurationchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondurationchange"].get, "get ondurationchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ondurationchange"].set, "set ondurationchange");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onemptied', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onemptied"].get, "get onemptied");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onemptied"].set, "set onemptied");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onended', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onended"].get, "get onended");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onended"].set, "set onended");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onerror', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onerror"].get, "get onerror");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onerror"].set, "set onerror");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onfocus', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onfocus"].get, "get onfocus");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onfocus"].set, "set onfocus");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onformdata', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onformdata"].get, "get onformdata");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onformdata"].set, "set onformdata");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oninput', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oninput"].get, "get oninput");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oninput"].set, "set oninput");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oninvalid', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oninvalid"].get, "get oninvalid");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oninvalid"].set, "set oninvalid");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onkeydown', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onkeydown"].get, "get onkeydown");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onkeydown"].set, "set onkeydown");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onkeypress', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onkeypress"].get, "get onkeypress");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onkeypress"].set, "set onkeypress");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onkeyup', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onkeyup"].get, "get onkeyup");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onkeyup"].set, "set onkeyup");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onload', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onload"].get, "get onload");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onload"].set, "set onload");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onloadeddata', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onloadeddata"].get, "get onloadeddata");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onloadeddata"].set, "set onloadeddata");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onloadedmetadata', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onloadedmetadata"].get, "get onloadedmetadata");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onloadedmetadata"].set, "set onloadedmetadata");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onloadstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onloadstart"].get, "get onloadstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onloadstart"].set, "set onloadstart");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmousedown', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmousedown"].get, "get onmousedown");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmousedown"].set, "set onmousedown");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmouseenter', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmouseenter"].get, "get onmouseenter");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmouseenter"].set, "set onmouseenter");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmouseleave', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmouseleave"].get, "get onmouseleave");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmouseleave"].set, "set onmouseleave");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmousemove', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmousemove"].get, "get onmousemove");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmousemove"].set, "set onmousemove");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmouseout', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmouseout"].get, "get onmouseout");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmouseout"].set, "set onmouseout");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmouseover', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmouseover"].get, "get onmouseover");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmouseover"].set, "set onmouseover");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmouseup', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmouseup"].get, "get onmouseup");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmouseup"].set, "set onmouseup");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmousewheel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmousewheel"].get, "get onmousewheel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onmousewheel"].set, "set onmousewheel");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpause', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpause"].get, "get onpause");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpause"].set, "set onpause");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onplay', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onplay"].get, "get onplay");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onplay"].set, "set onplay");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onplaying', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onplaying"].get, "get onplaying");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onplaying"].set, "set onplaying");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onprogress', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onprogress"].get, "get onprogress");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onprogress"].set, "set onprogress");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onratechange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onratechange"].get, "get onratechange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onratechange"].set, "set onratechange");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onreset', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onreset"].get, "get onreset");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onreset"].set, "set onreset");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onresize', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onresize"].get, "get onresize");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onresize"].set, "set onresize");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onscroll', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onscroll"].get, "get onscroll");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onscroll"].set, "set onscroll");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onsecuritypolicyviolation', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onsecuritypolicyviolation"].get, "get onsecuritypolicyviolation");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onsecuritypolicyviolation"].set, "set onsecuritypolicyviolation");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onseeked', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onseeked"].get, "get onseeked");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onseeked"].set, "set onseeked");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onseeking', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onseeking"].get, "get onseeking");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onseeking"].set, "set onseeking");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onselect', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onselect"].get, "get onselect");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onselect"].set, "set onselect");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onslotchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onslotchange"].get, "get onslotchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onslotchange"].set, "set onslotchange");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onstalled', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onstalled"].get, "get onstalled");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onstalled"].set, "set onstalled");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onsubmit', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onsubmit"].get, "get onsubmit");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onsubmit"].set, "set onsubmit");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onsuspend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onsuspend"].get, "get onsuspend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onsuspend"].set, "set onsuspend");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontimeupdate', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontimeupdate"].get, "get ontimeupdate");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontimeupdate"].set, "set ontimeupdate");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontoggle', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontoggle"].get, "get ontoggle");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontoggle"].set, "set ontoggle");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onvolumechange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onvolumechange"].get, "get onvolumechange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onvolumechange"].set, "set onvolumechange");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwaiting', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwaiting"].get, "get onwaiting");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwaiting"].set, "set onwaiting");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwebkitanimationend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwebkitanimationend"].get, "get onwebkitanimationend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwebkitanimationend"].set, "set onwebkitanimationend");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwebkitanimationiteration', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwebkitanimationiteration"].get, "get onwebkitanimationiteration");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwebkitanimationiteration"].set, "set onwebkitanimationiteration");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwebkitanimationstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwebkitanimationstart"].get, "get onwebkitanimationstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwebkitanimationstart"].set, "set onwebkitanimationstart");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwebkittransitionend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwebkittransitionend"].get, "get onwebkittransitionend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwebkittransitionend"].set, "set onwebkittransitionend");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwheel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwheel"].get, "get onwheel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onwheel"].set, "set onwheel");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onauxclick', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onauxclick"].get, "get onauxclick");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onauxclick"].set, "set onauxclick");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ongotpointercapture', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ongotpointercapture"].get, "get ongotpointercapture");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ongotpointercapture"].set, "set ongotpointercapture");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onlostpointercapture', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onlostpointercapture"].get, "get onlostpointercapture");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onlostpointercapture"].set, "set onlostpointercapture");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerdown', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerdown"].get, "get onpointerdown");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerdown"].set, "set onpointerdown");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointermove', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointermove"].get, "get onpointermove");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointermove"].set, "set onpointermove");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerup', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerup"].get, "get onpointerup");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerup"].set, "set onpointerup");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointercancel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointercancel"].get, "get onpointercancel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointercancel"].set, "set onpointercancel");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerover', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerover"].get, "get onpointerover");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerover"].set, "set onpointerover");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerout', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerout"].get, "get onpointerout");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerout"].set, "set onpointerout");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerenter', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerenter"].get, "get onpointerenter");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerenter"].set, "set onpointerenter");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerleave', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerleave"].get, "get onpointerleave");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerleave"].set, "set onpointerleave");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onselectstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onselectstart"].get, "get onselectstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onselectstart"].set, "set onselectstart");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onselectionchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onselectionchange"].get, "get onselectionchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onselectionchange"].set, "set onselectionchange");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onanimationend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onanimationend"].get, "get onanimationend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onanimationend"].set, "set onanimationend");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onanimationiteration', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onanimationiteration"].get, "get onanimationiteration");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onanimationiteration"].set, "set onanimationiteration");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onanimationstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onanimationstart"].get, "get onanimationstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onanimationstart"].set, "set onanimationstart");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontransitionrun', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontransitionrun"].get, "get ontransitionrun");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontransitionrun"].set, "set ontransitionrun");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontransitionstart', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontransitionstart"].get, "get ontransitionstart");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontransitionstart"].set, "set ontransitionstart");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontransitionend', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontransitionend"].get, "get ontransitionend");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontransitionend"].set, "set ontransitionend");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontransitioncancel', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontransitioncancel"].get, "get ontransitioncancel");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["ontransitioncancel"].set, "set ontransitioncancel");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncopy', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncopy"].get, "get oncopy");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncopy"].set, "set oncopy");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncut', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncut"].get, "get oncut");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["oncut"].set, "set oncut");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpaste', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpaste"].get, "get onpaste");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpaste"].set, "set onpaste");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'dataset', undefined, true, true, undefined, function () {debugger},);sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["dataset"].get, "get dataset");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'nonce', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["nonce"].get, "get nonce");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["nonce"].set, "set nonce");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'autofocus', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["autofocus"].get, "get autofocus");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["autofocus"].set, "set autofocus");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'tabIndex', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["tabIndex"].get, "get tabIndex");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["tabIndex"].set, "set tabIndex");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'style', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["style"].get, "get style");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["style"].set, "set style");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'attachInternals', function attachInternals(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLElement.prototype.attachInternals)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'blur', function blur(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLElement.prototype.blur)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'click', function click(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLElement.prototype.click)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'focus', function focus(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLElement.prototype.focus)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'inert', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["inert"].get, "get inert");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["inert"].set, "set inert");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'enterKeyHint', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["enterKeyHint"].get, "get enterKeyHint");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["enterKeyHint"].set, "set enterKeyHint");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'virtualKeyboardPolicy', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["virtualKeyboardPolicy"].get, "get virtualKeyboardPolicy");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["virtualKeyboardPolicy"].set, "set virtualKeyboardPolicy");
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerrawupdate', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerrawupdate"].get, "get onpointerrawupdate");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onpointerrawupdate"].set, "set onpointerrawupdate");

sandbox_vm2.defineProperty(HTMLElement.prototype, 'onbeforematch', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onbeforematch"].get, "get onbeforematch");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLElement.prototype)["onbeforematch"].set, "set onbeforematch");

Object.setPrototypeOf(HTMLElement.prototype, Element.prototype);