HTMLBodyElement = function HTMLBodyElement(){
            sandbox_vm2.throwError("TypeError", "Illegal constructor")
}
sandbox_vm2.func_set_native(HTMLBodyElement)
sandbox_vm2.rename(HTMLBodyElement.prototype, "HTMLBodyElement")

Object.setPrototypeOf(HTMLBodyElement.prototype,HTMLElement.prototype)
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'text', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["text"].get, "get text");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["text"].set, "set text");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'link', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["link"].get, "get link");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["link"].set, "set link");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'vLink', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["vLink"].get, "get vLink");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["vLink"].set, "set vLink");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'aLink', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["aLink"].get, "get aLink");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["aLink"].set, "set aLink");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'bgColor', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["bgColor"].get, "get bgColor");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["bgColor"].set, "set bgColor");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'background', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["background"].get, "get background");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["background"].set, "set background");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onblur', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onblur"].get, "get onblur");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onblur"].set, "set onblur");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onerror', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onerror"].get, "get onerror");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onerror"].set, "set onerror");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onfocus', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onfocus"].get, "get onfocus");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onfocus"].set, "set onfocus");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onload', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onload"].get, "get onload");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onload"].set, "set onload");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onresize', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onresize"].get, "get onresize");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onresize"].set, "set onresize");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onscroll', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onscroll"].get, "get onscroll");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onscroll"].set, "set onscroll");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onafterprint', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onafterprint"].get, "get onafterprint");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onafterprint"].set, "set onafterprint");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onbeforeprint', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onbeforeprint"].get, "get onbeforeprint");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onbeforeprint"].set, "set onbeforeprint");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onbeforeunload', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onbeforeunload"].get, "get onbeforeunload");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onbeforeunload"].set, "set onbeforeunload");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onhashchange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onhashchange"].get, "get onhashchange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onhashchange"].set, "set onhashchange");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onlanguagechange', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onlanguagechange"].get, "get onlanguagechange");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onlanguagechange"].set, "set onlanguagechange");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onmessage', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onmessage"].get, "get onmessage");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onmessage"].set, "set onmessage");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onmessageerror', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onmessageerror"].get, "get onmessageerror");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onmessageerror"].set, "set onmessageerror");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onoffline', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onoffline"].get, "get onoffline");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onoffline"].set, "set onoffline");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'ononline', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["ononline"].get, "get ononline");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["ononline"].set, "set ononline");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onpagehide', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onpagehide"].get, "get onpagehide");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onpagehide"].set, "set onpagehide");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onpageshow', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onpageshow"].get, "get onpageshow");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onpageshow"].set, "set onpageshow");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onpopstate', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onpopstate"].get, "get onpopstate");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onpopstate"].set, "set onpopstate");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onrejectionhandled', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onrejectionhandled"].get, "get onrejectionhandled");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onrejectionhandled"].set, "set onrejectionhandled");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onstorage', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onstorage"].get, "get onstorage");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onstorage"].set, "set onstorage");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onunhandledrejection', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onunhandledrejection"].get, "get onunhandledrejection");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onunhandledrejection"].set, "set onunhandledrejection");
sandbox_vm2.defineProperty(HTMLBodyElement.prototype, 'onunload', undefined, true, true, undefined, function () {debugger},function (value) {debugger});sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onunload"].get, "get onunload");sandbox_vm2.func_set_native(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype)["onunload"].set, "set onunload");


