HTMLElement = function HTMLElement() {
    sandbox_vm2.throwError("TypeError", "Illegal constructor");
}
sandbox_vm2.func_set_native(HTMLElement);
sandbox_vm2.rename(HTMLElement.prototype, "HTMLElement");


sandbox_vm2.defineProperty(HTMLElement.prototype, 'title', '', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'lang', '', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'translate', true, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'dir', '', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'hidden', false, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'accessKey', '', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'draggable', false, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'spellcheck', true, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'autocapitalize', '', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'contentEditable', 'inherit', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'isContentEditable', false, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'inputMode', '', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'offsetParent', {}, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'offsetTop', 0, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'offsetLeft', 0, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'offsetWidth', 40, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'offsetHeight', 40, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'innerText', '', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'outerText', '', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onbeforexrselect', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onabort', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onblur', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncancel', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncanplay', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncanplaythrough', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onchange', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onclick', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onclose', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncontextlost', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncontextmenu', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncontextrestored', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncuechange', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondblclick', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondrag', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondragend', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondragenter', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondragleave', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondragover', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondragstart', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondrop', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ondurationchange', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onemptied', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onended', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onerror', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onfocus', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onformdata', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oninput', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oninvalid', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onkeydown', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onkeypress', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onkeyup', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onload', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onloadeddata', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onloadedmetadata', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onloadstart', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmousedown', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmouseenter', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmouseleave', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmousemove', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmouseout', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmouseover', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmouseup', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onmousewheel', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpause', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onplay', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onplaying', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onprogress', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onratechange', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onreset', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onresize', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onscroll', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onsecuritypolicyviolation', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onseeked', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onseeking', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onselect', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onslotchange', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onstalled', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onsubmit', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onsuspend', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontimeupdate', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontoggle', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onvolumechange', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwaiting', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwebkitanimationend', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwebkitanimationiteration', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwebkitanimationstart', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwebkittransitionend', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onwheel', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onauxclick', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ongotpointercapture', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onlostpointercapture', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerdown', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointermove', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerup', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointercancel', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerover', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerout', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerenter', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerleave', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onselectstart', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onselectionchange', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onanimationend', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onanimationiteration', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onanimationstart', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontransitionrun', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontransitionstart', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontransitionend', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'ontransitioncancel', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncopy', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'oncut', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpaste', null, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'dataset', {}, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'nonce', '', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'autofocus', false, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'tabIndex', -1, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'style', {}, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'attachInternals', function attachInternals(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLElement.prototype.attachInternals);
sandbox_vm2.defineProperty(HTMLElement.prototype, 'blur', function blur(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLElement.prototype.blur);
sandbox_vm2.defineProperty(HTMLElement.prototype, 'click', function click(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLElement.prototype.click);
sandbox_vm2.defineProperty(HTMLElement.prototype, 'focus', function focus(){debugger;}, true, true, true); sandbox_vm2.func_set_native(HTMLElement.prototype.focus);
sandbox_vm2.defineProperty(HTMLElement.prototype, 'inert', false, true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'enterKeyHint', '', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'virtualKeyboardPolicy', '', true, true, true)
sandbox_vm2.defineProperty(HTMLElement.prototype, 'onpointerrawupdate', null, true, true, true)

sandbox_vm2.defineProperty(HTMLElement.prototype, 'onbeforematch', null, true, true, true)



sandbox_vm2.defineProperty(HTMLElement, '_prevClass', 'slide-verify-slider-mask-item', true, true, true)

Object.setPrototypeOf(HTMLElement.prototype, Element.prototype);